name: tests

on: [push, pull_request]


jobs:
  apool-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest dask[distributed]

    - name: Testing
      run: |
        coverage run --parallel-mode -m pytest --doctest-modules apool
        coverage combine
        coverage report -m
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
